[package]
name = "hermes"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"], default-features = false }
heapless = "0.7"
nb = "1"
defmt = "0.3"

postcard = { version = "1" }
fastrand = { version = "2.3", default-features = false }

embassy-futures = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[profile.dev]
opt-level = 1
