[package]
name = "hermes"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
heapless = "0.7"
embedded-hal-nb = "1"
nb = "1"
defmt = "0.3"

postcard = { version = "1" }
fastrand = { version = "2.3", default-features = false }

pin-project = "1"

# [profile.release]
# lto = true
# codegen-units = 1
# opt-level = 3

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
