[package]
name = "usb-daisy-uart_bluepill"
version = "0.1.0"
edition = "2021"

# -------------------------------------------------------
#                   EMBASSY DEPENDENCIES
# -------------------------------------------------------

[dependencies.embassy-stm32]
version = "0.2"
features = ["defmt", "stm32f103c8", "unstable-pac", "memory-x", "time-driver-any", "exti", "chrono"]

[dependencies.embassy-sync]
version = "0.6"
features = ["defmt"]

[dependencies.embassy-executor]
version = "0.7"
features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "nightly"]

[dependencies.embassy-time]
version = "0.4"
features = ["tick-hz-32_768", "defmt", "defmt-timestamp-uptime"]

[dependencies.embassy-usb]
version = "0.4"
# features = ["max-interface-count-1", "max-handler-count-1"]

[dependencies.embassy-futures]
version = "0.1"

# -------------------------------------------------------

[dependencies]
defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }

embedded-alloc = "0.6"

# Cortex stuff
cortex-m = { version = "0.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7"
critical-section = "1"

hermes = { path = "../../../IGVC-25/hermes" }
hermes_link_embassy_rb = { path = "../../../IGVC-25/hermes/impls/embassy_rb" }
hermes_link_embassy_usb = { path = "../../../IGVC-25/hermes/impls/embassy_usb" }
hermes_link_embassy_eio = { path = "../../../IGVC-25/hermes/impls/embassy_eio" }

# -------------------------------------------------------

[profile.release]
debug = 2
lto = true
opt-level = 3
codegen-units = 1

[profile.dev]
opt-level = 1
